/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  z as zod
} from 'zod'


/**
 * @summary List Receipts
 */
export const listReceiptsReceiptsGetResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "key": zod.string(),
  "data": zod.any(),
  "timestamp": zod.string()
})
export const listReceiptsReceiptsGetResponse = zod.array(listReceiptsReceiptsGetResponseItem)


/**
 * @summary Create Receipt
 */
export const createReceiptReceiptsPostResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "key": zod.string(),
  "data": zod.any(),
  "timestamp": zod.string()
})


/**
 * @summary Get Receipt
 */
export const getReceiptReceiptsIdGetParams = zod.object({
  "id": zod.string()
})

export const getReceiptReceiptsIdGetResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "key": zod.string(),
  "data": zod.any(),
  "timestamp": zod.string()
})


/**
 * @summary Receipt Image
 */
export const receiptImageReceiptsIdImageGetParams = zod.object({
  "id": zod.string()
})

export const receiptImageReceiptsIdImageGetResponse = zod.any()


/**
 * @summary General Insights
 */
export const generalInsightsInsightsGeneralGetResponse = zod.string()


/**
 * @summary Sustainability Insights
 */
export const sustainabilityInsightsInsightsSustainabilityGetResponse = zod.string()


